### ISSUE TITLE
Dose the network use depth pre-training?

### ISSUE THREAD

**Issue by Cc-Hy** [cnexah/DeepLineEncoding#1]
Hello,
I'd like to ask whether the network is pre-trained on a depth dataset.
Thanks.

**Comment by cnexah** [comment]
Hello!
For the 3d object detection task, we trained only on the KITTI 3d object detection dataset. And we will release the code after the CVPR deadline. 
Thank you!!

**Comment by Cc-Hy** [comment]
Thanks for answering.
