### ISSUE TITLE
How can I use multi gpu training?

### ISSUE THREAD

**Issue by sekimcb** [cnexah/DeepLineEncoding#3]
When I try training, i got the error message

RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 10.92 GiB total capacity; 10.28 GiB already allocated; 29.44 MiB free; 10.37 GiB reserved in total by PyTorch)

Is there any option to use multi gpu??

**Comment by cnexah** [comment]
Yes 
CUDA_VISIBLE_DEVICES=$GPUS python -m torch.distributed.launch --nproc_per_node=$NUM_GPUS scripts/train.py --config=config/config.py --world_size=$NUM_GPUS # for multiple GPUs

But there might be bugs in multi-GPU training in the old version of VisualDet3D.
You might need to update the code following the new VisualDet3D.

**Comment by sekimcb** [comment]
Thank you for super quick reply!! It works :)
