### ISSUE TITLE
What is bt and dht in 'yolomono3d_core.py'?

### ISSUE THREAD

**Issue by sekimcb** [cnexah/DeepLineEncoding#4]
Hello, again.

I wonder what do 'bt' and 'dht' mean in 'yolomono3d_core.py'. 

And can I use hough transform idea as your model to MonoFlex model? 
If I could, is it ok use 'DLA' backbone to apply hough transform? 

Thank you

**Comment by cnexah** [comment]
Thank you for your interest!

'bt' is the abbreviation for 'bottleneck', and is applied to reduce the number of feature channels.
'dht' is the abbreviation for 'deep Hough transform', and is applied to perform Hough transform on feature maps.

Yes, I think the idea of Hough transform can be applied to various models and backbones.

**Comment by sekimcb** [comment]
Thank you for your reply!! 
It helps me to understand!!

I have one more question... :) 
Where can I find "Line Pooling" module code in yours? 

Thank you
Sincerely

**Comment by cnexah** [comment]
The 'dht_backbone' in yolomono3d_core.py represents the 'Line Pooling'  module.
https://github.com/cnexah/DeepLineEncoding/blob/adbe91824480ebcd8cbb14f0cc766b465386b4b8/object_detection/visualDet3D/networks/detectors/yolomono3d_core.py#L51

**Comment by sekimcb** [comment]
Aha got it!

Thank you very much!
