### ISSUE TITLE
How can I visualize featuremap and lines as paper?

### ISSUE THREAD

**Issue by sekimcb** [cnexah/DeepLineEncoding#5]
Hello, 

I wonder is there any visualization tool or script for visualize featuremap and lines like Figure.3. in your paper?

Thank you

**Comment by cnexah** [comment]
Yes. Could you give me your email to receive the files?

**Comment by sekimcb** [comment]
kse990088@gmail.com 

Thank you very much!

**Comment by cnexah** [comment]
I have sent it to you.

**Comment by sekimcb** [comment]
I got it! Thank you for sharing!

Happy new year!
